cuda/templates/BUILD.local_toolchain_nvcc

This PR simply removes the `@platforms//cpu:x86_64` constraint from the nvcc toolchain template. I'm not sure if this is the preferred way to achieve this, but CUDA on linux is compatible with aarch64 for both servers and embedded use cases. This enables builds with on these platforms as well.

eliminate cpu architecture constraint for nvcc

---

cuda/private/rules/cuda_library.bzl

if you specify a `cuda_library` with no sources, an error is thrown here due to there being nothing to link. This adds a check that `library_to_link` is not None before proceeding.

add defensive wiring for header-only libraries

---

cuda/private/providers.bzl

AGX Orin has compute capability 8.7, and Hopper has compute capability 9.0. Add both to providers to enable targeting these platforms.

add agx orin & hopper compute capabilities

---

cuda/private/toolchain_configs/nvcc.bzl

It is common to compile on machines that don't have a GPU installed e.g. RBE build nodes. Also setting default compilation to use the native arch is not as reproducible because it is dependent upon the hardware of the build node that the compiler is invoked on.
Turn off the arch_native feature by default to make the default configuration more reproducible.

Disable arch_native by default

---

cuda/private/repositories.bzl

Tell bazel that the configuration is inspecting the local system and drawing from local installed files for the cuda toolchain.

Set local and configure on local_cuda repository

---

.github/workflows/build-tests.yaml
.github/workflows/docs-tests.yaml
.github/workflows/utilities-tests.yaml

Avoid the wasting of public CI resource and make it a little bit eco-friendlier.

Make CI eco-friendly by avoiding run pipelines twice on push within PR

---

README.md
cuda/BUILD.bazel
examples/if_cuda/BUILD.bazel
examples/if_cuda/README.md
examples/if_cuda/if_cuda.bzl
examples/if_cuda/main.cpp

Follows #31 with minor changes to the `if_cuda` and expansion of related documentation.

Enable rules_cuda by default, add docs

---

cuda/private/actions/compile.bzl
cuda/private/actions/dlink.bzl
cuda/private/toolchain.bzl

Adds the ability to specify files that are needed by the compiler toolchain which is the first step towards being able to create a hermetic cuda toolchain.

Add option to add files to the toolchain configuration

---

cuda/private/rules/common.bzl

Libraries such as Thrust have .inl files that might exposed in headers. This PR allow that as a valid header name.

Allow inl as header suffix.

---

.bcr/config.yml
.bcr/metadata.template.json
.bcr/presubmit.yml
.bcr/source.template.json

Adds configuration for the publish-to-bcr app which auto publishes a PR to the bazel-central-registry whenever a release is made.

Add publish-to-bcr configuration

---

cuda/private/toolchain_configs/nvcc.bzl

As is, nvlink will use the system compiler configuration to produce objects, resulting in an error when building //rules_cuda/examples/rdc:main  in 2 cases:
* When using a custom gcc toolchain that is a different version than your system install, nvcc will fail to find gcc after nvlink-ing
* When cross-compiling, nvlink will produce objects for the host architecture instead of the target architecture
This change is also likely needed in nvcc_msvc.bzl, but I have no way to test.

Add host compiler flag to device link step

---

cuda/private/cuda_helper.bzl
cuda/private/rules/cuda_library.bzl

This fixes a bug where the transitive flags aren't propagated correctly in all cases. Notably adds the _builtin_deps dependency to pick up context from the configured `//cuda:runtime` dependency.

Use merge_cc_infos to calculate common flags

---

.github/workflows/build-tests.yaml

Linearize the matrix. Add toolkit from apt for #74 test.

Change building test combination

---

.github/workflows/build-tests.yaml
cuda/private/repositories.bzl
cuda/runtime/BUILD.local_cuda

The rules for this repository do not currently work with the following commonly used CUDA configuration: https://lambdalabs.com/lambda-stack-deep-learning-software
The reason is because the Lambda deep stack installs CUDA in /usr/bin, which breaks a couple of assumptions with this software.
In particular:
- /usr/lib64 is the wrong path here, /usr/lib/x86_64-linux-gnu/ is correct. 
- /usr/bin/** is invalid since it contains recursive symlinks
This fixes those two issues.

Various fixes to get rules_cuda to work with Lambda-stack

---

.github/workflows/build-tests.yaml
.github/workflows/release.yaml

[Test Examples Build (CUDA 10.1.243 on ubuntu-18.04)](https://github.com/bazel-contrib/rules_cuda/actions/runs/4543560869/jobs/8008403992)
This is a scheduled Ubuntu-18.04 brownout. The Ubuntu-18.04 environment is deprecated and will be removed on April 1st, 2023. For more details, see https://github.com/actions/runner-images/issues/6002

Stop using ubuntu-18.04

---

cuda/private/cuda_helper.bzl

For example, if users pass options like `--compiler-options=...`, equivalent to `-Xcompiler`, however, will be disallowed due to a match with `opt.startswith("--compile")`.

Relax the _check_opts impl

---

renovate.json

In #117, bzlmod deps is auto updated but is not desired. Configure renovate bot to ignore `MODULE.bazel` scanning to avoid future auto updating.

Ignore MODULE.bazel for renovate bot

---

cuda/defs.bzl
cuda/private/os_helpers.bzl
cuda/runtime/BUILD.local_cuda

libcudart.so is a symlink to a versioned .so file, and the SONAME
specifies the versioned file, which means that at runtime the dynamic
linker will look for the versioned file, so we need to import the
versioned files.
Fixes: https://github.com/bazel-contrib/rules_cuda/issues/113

Include versioned so files in cuda_runtime

---

cuda/private/toolchain_configs/nvcc.bzl
tests/flag/BUILD.bazel

this makes the debug info for both host and device code the same
(i.e. --generate-line-info does for device code what -g1 does for
host code).
This is an intuitive result IMO.

set nvcc --generate-line-info when compilation_mode=fastbuild

---

.github/workflows/build-tests.yaml
cuda/private/rules/cuda_library.bzl
examples/rdc/BUILD.bazel

This allows a `cuda_library` that was built with `rdc=True` to be
depended upon by another such library. This is convenient as such a
library can be consumed by either another `cuda_library` OR a
`cc_library`.
Note: if we have this, I'm not sure why we need a separate cuda_objects
rule anymore. Perhaps it can be removed in a later PR.
Change-Id: I1014d28a0ab3a9c76b788821211b13c4a9956d2a

have cuda_library output RDC

---

cuda/templates/BUILD.local_toolchain_nvcc
cuda/templates/BUILD.local_toolchain_nvcc_msvc

This is harmless, as fatbinary is not used in nvcc. It is only used when `_wrapper_device_link` is called in clang toolchain.

Fix obvious typo of templates

---

cuda/private/actions/compile.bzl
cuda/private/actions/dlink.bzl

Compile the newly added example with `_wrapper_device_link` with rdc cause artifact name conflict
https://github.com/bazel-contrib/rules_cuda/blob/0503ead4724517db445796cbcdfc8400ce88c853/examples/rdc/BUILD.bazel#L39-L44
The reason is because our `compile` always compile to `<target_output_dir>/_objs`:
```
cuda_library(name="b") --> artifact base name is `b` during `compile`
with `compile` for following srcs
"b.cu" ------------------> artifact `<target_output_dir>/_objs/b.rdc.o`
`fatbin.cu` ------rdc----> artifact `<target_output_dir>/_objs/b.rdc.o`
After this PR:
"b.cu" ------------------> artifact `<target_output_dir>/_objs/b.rdc.o`
`fatbin.cu` ------rdc----> artifact `<target_output_dir>/_objs/_dlink/b.rdc.o`
```
Note we reserve the `_prefix` keyword params for future change and keep …

Fix _wrapper_device_link artifact name conflict

---

cuda/private/repositories.bzl

`MODULE.bazel` is already updated to the new versionin 09e10b36f02c2e4bca81a7a8c77b094ccc59aa87, sync them up.
This also includes the `expand_template` in new release, and it is used in the upcomming integration example and test.

Update bazel_skylib to 1.4.2

---

cuda/private/rules/common.bzl

NVCC is perfectly happy to compile these, and this is actually useful for my use case of having a single source that is compilable both as a regular cc_library and a cuda_library, depending on preprocessor directives inside the code.

allow .cpp and .cc files in srcs

---

.github/workflows/build-tests.yaml
.github/workflows/release.yaml

ubuntu-22.04 repo only has 11.7 as the minimium version of cuda toolkit, it seems that nvidia has pulled some old versions from the apt repo.

Update matrix versions

---

.bcr/source.template.json

This is the reason that the BCR publish failed when the last release was cut.

Fix url for BCR publish app

---

cuda/private/cuda_helper.bzl
cuda/private/providers.bzl
cuda/private/rules/cuda_library.bzl
cuda/private/rules/cuda_objects.bzl

1. `cuda_objects` now returns `CcInfo` with linking context, thus, the `cc_library` deps can correctly propagate to `cuda_library`
2. correctly handle transitive objects for archiving and device linking.
This fixed static linking issue introduced by #125, and partially address some concerns mentioned in #164

Improve RDC

---

cuda/private/macros/cuda_test.bzl

Srcs and hdrs have to be excluded from the cc_test because we want them to be compiled with nvcc

Fix cuda_test

---

cuda/private/cuda_helper.bzl

nvcc shells out to the host compiler, but does not set the `--sysroot` option. In the case of a hermetic cc_toolchain the host compiler will then fail to find the system includes.
See https://github.com/lalten/mre_rules_cuda-sysroot/tree/main for a demonstration
See discussion on Bazel Slack: https://bazelbuild.slack.com/archives/C043E282KUG/p1698396425839079

Pass through `--sysroot` to host compiler

---

cuda/private/macros/cuda_binary.bzl
cuda/private/macros/cuda_test.bzl

Add alwayslink to cuda_binary and cuda_test macros

---

examples/if_cuda/README.md

The doc "bazel build //if_cuda:main --@rules_cuda//cuda:enable`" does not seem right.

Fix a typo in `if_cuda` doc

---

.gitignore

`MODULE.bazel.lock` file is a mechanism under `bzlmod` intended to record package and dependency versions (see Bazel documentation https://bazel.build/external/lockfile). However, this mechanism is not yet stable, for example, it does not seem to guarantee content consistency, and causes version control conflicts, for example see https://github.com/bazelbuild/bazel/issues/20369
So at this moment we put `MODULE.bazel.lock` files (including root directory and subdirectories) into `.gitignore` file.
Resolves #223

Ignore MODULE.bazel.lock file

---

.github/workflows/build-tests.yaml

We start to observe (so some old bazel versions)
```
tmpxft_00000002_00000001-6_b.cudafe1.stub.c:1:10: fatal error: tmpxft_00000002_00000001-6_b.cudafe1.stub.c: No such file or directory
```
Some previous steps show `(5 actions running)` in the log, indicating we are using some more powerful machine. Limiting parallel jobs to 1 should workaround the problem.

ci: avoid nvcc /tmp race condition

---

.github/workflows/github-pages.yaml

ci: disable doc test workflow cache to avoid excessive space wasting

---

examples/MODULE.bazel

Change example rules_cuda to a version that is availbe within the Bazel Central Registry

Change example rules_cuda version

---

README.md

Document how to use rules_cuda with Bzlmod

Document how to use rules_cuda with Bzlmod

---

cuda/runtime/BUILD.local_cuda

`libcupti.so` can sometimes be located under `cuda/extras/CUPTI/lib64/` instead

Do not assume libcupti.so location

---

.github/workflows/release.yaml

CI log:
```console
ERROR: Skipping '//...': error loading package under directory '': error loading package '~/.cache/bazel-repo/bazel/_bazel_runner/c7158fce5becee297c399541ca8c3db4/install/rules_java/toolchains': at /home/runner/work/rules_cuda/rules_cuda/~/.cache/bazel-repo/bazel/_bazel_runner/c7158fce5becee297c399541ca8c3db4/install/rules_java/toolchains/java_toolchain_alias.bzl:17:6: Label '//java/common:java_common.bzl' is invalid because 'java/common' is not a package; perhaps you meant to put the colon here: '//:java/common/java_common.bzl'?
ERROR: error loading package under directory '': error loading package '~/.cache/bazel-repo/bazel/_bazel_runner/c7158fce5becee297c399541ca8c3db4/install/rules_java/toolchains': at /home/runner/work/rules_cuda/rules_cuda/~/.cache/bazel-repo/bazel …
```

ci: use absolute path for XDG_CACHE_HOME as github actions and bazel doesn't resolve `~` automatically

---

.github/workflows/utilities-tests.yaml

This reveal the release pipeline failure

ci: cover major bazel releases in utilities tests

---

tests/flag/flag_validation_test.bzl

Partially fix test failures triggered by #262
Workaround utilities test when bzlmod is enabled:
```
ERROR: Traceback (most recent call last):
File "/home/runner/work/rules_cuda/rules_cuda/tests/flag/flag_validation_test.bzl", line 98, column 61, in <toplevel>
cuda_library_sm61_flag_test = _create_cuda_library_flag_test(config_settings_sm61)
File "/home/runner/work/rules_cuda/rules_cuda/tests/flag/flag_validation_test.bzl", line 63, column 29, in _create_cuda_library_flag_test
return analysistest.make(
File "/home/runner/.cache/bazel/_bazel_runner/c7158fce5becee297c399541ca8c3db4/external/bazel_skylib~/lib/unittest.bzl", line [28](https://github.com/bazel-contrib/rules_cuda/actions/runs/10286317527/job/28467427384?pr=262#step:6:29)5, column 51, in _make_analysis_test
test_transition = …
```

test: workaround label resolving with bzlmod

---

.github/workflows/build-tests.yaml
MODULE.bazel
cuda/extensions.bzl
examples/if_cuda/BUILD.bazel
tests/integration/BUILD.to_symlink
tests/integration/MODULE.bazel
tests/integration/WORKSPACE.bazel
tests/integration/test_all.sh
tests/integration/toolchain_none/BUILD.bazel
tests/integration/toolchain_none/MODULE.bazel
tests/integration/toolchain_root/BUILD.bazel
tests/integration/toolchain_root/MODULE.bazel
tests/integration/toolchain_rules/BUILD.bazel
tests/integration/toolchain_rules/MODULE.bazel

Superserde #239 
In https://github.com/bazel-contrib/rules_cuda/pull/263#issuecomment-2273722073 a new error popup as expected.
It is caused by the unittest secretly setup our module (rules_cuda, current root module as of invocation of `bazel` command) as an external module under testing, then the `local_cuda` is ignore in this case. We shall allow call to module_extenion in both root module and our module.
This in principle also fixes #238.

fix(bzlmod): allow both root module and our module to call cuda.local_toolchain

---

README.md

Documented in https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

Make it clear that "integrity" field expects SRI

---

.bcr/presubmit.yml

- add basic presubmit yaml to pass bcr ci for the PR generated automatically
- related to https://github.com/bazelbuild/bazel-central-registry/pull/2731

fix(bcr): add basic presubmit yaml

---

cuda/runtime/BUILD.local_cuda

[NVRTC](https://docs.nvidia.com/cuda/nvrtc/) (runtime compilation library for CUDA C++) is part of the CUDA Toolkit. This PR adds a target for the NVRTC library.

Add NVRTC to local_cuda

---

docs/MODULE.bazel

Initially unblocks [upgrade to Bazel 8](https://github.com/bazel-contrib/rules_cuda/pull/308)
For the PR upgrading Bazel to v8 (where `WORKSPACE` is disabled by default), the first error is because of the absence of the `io_bazel_stardoc` in [this action run](https://github.com/bazel-contrib/rules_cuda/actions/runs/12565394242/job/35029612602?pr=308).
For this, I added the `repo_name` to add an alias since [some usage](https://github.com/bazel-contrib/rules_cuda/blob/d5416e1fadbfe79ee0b4bf4165dc3cd78ce68242/docs/BUILD.bazel#L2) still expects the name to be `io_bazel_stardoc`.
I also noticed that WORKSPACE has stardoc v0.7.0 but MODULE.bazel is still lagging behind, therefore bumped it up to match.

Make stardoc in sync with WORKSPACE usage

---

cuda/private/macros/cuda_test.bzl

The native.cc_test rule has a `data` attribute that is not exposed in the cuda_test rule. This change allows the cuda_test rule to specify the `data` attribute, and plumb it down to the native.cc_test rule.

fix; Allow cuda_test to specify the `data` attribute.

---

cuda/private/actions/compile.bzl
cuda/private/actions/dlink.bzl
cuda/private/cuda_helper.bzl
cuda/private/toolchain_configs/clang.bzl
cuda/private/toolchain_configs/nvcc.bzl

Possibly supersede #313.
This should be fully address and tested in the future cross compile support.

feat: make sysroot a feature

---

cuda/private/toolchain_configs/nvcc.bzl

Instead of reducing the PATH of the `cpp_compile` action to only the dir of the host compiler, we can query we toolchain for the configured PATH and append the directory of the host compiler.
This way 1) nvcc can still find the host compiler from the PATH and 2) a potential compiler wrapper script that acts as the host compiler can still find its dependencies.

fix(nvcc): append to `cpp_compile` `PATH`

---

.github/workflows/github-pages.yaml

Skip v0.2.5 since it is only one minor change.

ci(docs): gen new docs

---

.github/release_notes.template
MODULE.bazel
README.md
WORKSPACE.bazel
cuda/extensions.bzl
cuda/private/repositories.bzl
cuda/repositories.bzl
docs/MODULE.bazel
docs/user_docs.bzl
examples/MODULE.bazel
examples/WORKSPACE.bazel
tests/integration/toolchain_none/MODULE.bazel
tests/integration/toolchain_root/MODULE.bazel

Related to #283
1. `rules_cuda_dependencies` only pull in bazel deps for rules_cuda and split the `local_cuda` part into newly added `rules_cuda_toolchains`
2. rename `local_toolchain` as `toolkit` for bzlmod

refactor!: change for hermetic with minor user interface breaking

---

cuda/extensions.bzl
cuda/private/compat.bzl
cuda/private/repositories.bzl
cuda/private/template_helper.bzl
cuda/private/templates/BUILD.cudart
cuda/private/templates/BUILD.local_cuda_shared
cuda/private/templates/README.md
cuda/private/templates/defs.bzl.tpl
cuda/private/templates/registry.bzl
cuda/repositories.bzl
tests/integration/test_all.sh
tests/integration/toolchain_redist/BUILD.bazel
tests/integration/toolchain_redist/MODULE.bazel

Related: #283
This adds a new repo rule `cuda_component` and existing repo rule is adapt respectively.
We organize the generated repo as follows, for both `local_cuda` and `local_cuda_<component_repo_name>`
```
<repo_root>              # bazel unconditionally creates a directory for us
├── %{component_name}/   # cuda for local ctk, component name otherwise
│   ├── include/         #
│   └── %{libpath}/      # lib or lib64, platform dependent
├── defs.bzl             # generated
├── BUILD                # generated from BUILD.local_cuda and one/all of the component(s)
└── WORKSPACE            # generated
```
If the repo is `local_cuda`, we additionally generate toolchain config as follows
```
<repo_root>
└── toolchain/
├── BUILD            # the default nvcc toolchain
├── clang/ …
```

feat: hermetic ctk with deliverable

---

cuda/extensions.bzl
cuda/private/repositories.bzl
cuda/private/template_helper.bzl
cuda/private/templates/BUILD.redist_json
cuda/private/templates/redist.bzl.tpl
cuda/repositories.bzl
tests/integration/test_all.sh
tests/integration/toolchain_redist_json/BUILD.bazel
tests/integration/toolchain_redist_json/MODULE.bazel
tests/integration/toolchain_redist_json/WORKSPACE.bazel

#283
`cuda_redist_json` repo rule download the `redistrib.json` (redist_json) from the `urls`, or download from nvidia's default repo if only `version` is specified. In the repo, we generate a `redist.bzl` file. The `redist.bzl` contains macros with wrapped `cuda_component` repo rules of the components specified in the `cuda_redist_json`'s `components` attribute.
For example,
```starlark
cuda_redist_json(
name = "rules_cuda_redist_json",
components = [
"cccl",
"cudart",
"nvcc",
],
version = "12.6.3",
)
```
- Downloads `redistrib.json` from `https://developer.download.nvidia.com/compute/cuda/redist/redistrib_12.6.3.json`
- Generates a `redist.bzl` with the content as follows:
```
def rules_cuda_components():
cuda_component(
name = "local_cuda_cccl_v12.6.77",
component_name = "cccl",
) …
```

feat: `load("@rules_cuda_redist_json//:redist.bzl", "rules_cuda_components")`

---

cuda/private/rules/cuda_library.bzl
cuda/private/rules/cuda_objects.bzl
cuda/private/toolchain.bzl
cuda/private/toolchain_configs/clang.bzl
cuda/private/toolchain_configs/nvcc.bzl
cuda/private/toolchain_configs/nvcc_msvc.bzl
docs/developer_docs.bzl

This PR tries to use `use_cpp_toolchain` from `@bazel_tools` instead of the copied definition earlier.

refactor: remove use_cpp_toolchain

---

cuda/private/cuda_helper.bzl

These are set if your `cuda_library` depends on a `cc_library` that is
part of another bazel module besides the main one and you set
`--features=external_include_paths`
We could thread these through with a different variable but they end up
being treated the same so I don't think it matters.

Add CcInfo external_includes

---

cuda/private/repositories.bzl
cuda/private/template_helper.bzl
cuda/private/templates/BUILD.toolchain_clang
cuda/private/toolchain.bzl

When a compatible `cc_toolchain` is registered, prefer that when compiler_executable is not set or set to non-hermetic system executable.
With this PR's change, I was able to just make my pre-configured `toolchains_llvm`-based toolchain be automatically selected. Without this, I had to fully specifiy my own local toolchain with a `compiler_executable` pointing to the llvm_toolchain's clang binary.
After #330 
Fixes #324 
TODO:

feat: automatically detect compiler_executable from registered cc_toolchain

---

.github/workflows/build-tests.yaml
.github/workflows/integration-tests.yaml
.github/workflows/utilities-tests.yaml

Account for deprecation of `ubuntu-20.04`
https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/

Update deprecated CI runners

---

cuda/private/repositories.bzl
cuda/private/template_helper.bzl
cuda/private/templates/BUILD.clang_compiler_deps
cuda/private/templates/BUILD.toolchain_clang

Partially part of #283 
This PR adds the missing piece of hermetic CUDA compilation with clang. The provided `compiler_deps` repo (alias cuda_nvcc) wasn't enough for clang to infer everything from. Typically, it's documented in multiple places ([(1)](https://llvm.org/docs/CompileCudaWithLLVM.html#id3), [(2)](https://reviews.llvm.org/D42642)) that clang expects the entire CUDA toolkit and there is no recommended "minimal" CUDA setup. Nevertheless, I found that `cccl`, `nvcc`, `cudart`, `nvvm` components were enough.
Surprisingly, I didn't need the `version.json` or `version.txt` file anymore so I removed the logic to generate the root `version.json` file.
In `config_clang` we create a new folder called `clang_compiler_deps` where we collect `bin`, `lib`, `include` files from the required …

feat: hermetic CUDA clang support 

---

cuda/private/os_helpers.bzl
tests/utils/cc_import_versioned_sos/BUILD.bazel
tests/utils/cc_import_versioned_sos/cc_import_versioned_sos_test.bzl

Current way of importing versioned shared libraries (`cc_import` -> `cc_library`) places each part of a library in a separate directory under `_solib_*` (because mangled directory name depends on the name of importing target), which in turn generates a lot of entries in `RUNPATH` when linking to these libraries.
By specifying shared libraries directly in `srcs` attribute of `cc_library` it is possible to cut down number of these entries (because libraries will be imported by the same target).
Example for cuBLAS:
- before:
- solib symlinks:
```
_solib_k8
|-- _U_A_Arules_Ucuda++toolchain+local_Ucuda_S_S_Clibcublas.so.12.4.5.8___Ucuda_Slib64
|   `-- libcublas.so.12.4.5.8
|-- _U_A_Arules_Ucuda++toolchain+local_Ucuda_S_S_Clibcublas.so.12___Ucuda_Slib64
|   `-- libcublas.so.12
|-- …
```

Shorten `RUNPATH` when linking to versioned shared libraries

---

cuda/extensions.bzl
cuda/private/redist_json_helper.bzl

If the user does not specify the components to be downloaded, it can default to all of them.

If no components specified, use all components.
