cuda/runtime/BUILD.local_cuda

This adds basic support for curand, cufft, cusolver, cusparse, nvcc headers, and nvtx

add support for some cudax libraries

---

.github/workflows/build-tests.yaml
.github/workflows/utilities-tests.yaml

Run tests on pull requests so that we find breaks before they are merged.

Enable tests on pull requests

---

README.md
WORKSPACE
cuda/defs.bzl
cuda/private/repositories.bzl
cuda/repositories.bzl
docs/WORKSPACE.bazel
docs/user_docs.bzl
renovate.json

Initial work to align the repository with style guide outlined here: https://bazel.build/rules/deploying

refactor!: make structure consistent w/ rule guidelines

---

.bazelrc

Fix flag_alias

---

.bazelignore
.github/workflows/build-tests.yaml
.gitignore
WORKSPACE
examples/.bazelrc
examples/WORKSPACE.bazel
examples/basic/BUILD.bazel
examples/if_cuda/BUILD.bazel
examples/rdc/BUILD.bazel
examples/thrust/BUILD.bazel
tests/flag/BUILD.bazel

Make examples its own workspace

---

.github/workflows/ci.bazelrc
.github/workflows/release.yaml
.github/workflows/workspace_snippet.sh
examples/WORKSPACE.bazel

ci: create release automation

---

.github/workflows/docs-tests.yaml

Setup CI pipeline for testing docs generation

---

cuda/private/repositories.bzl
cuda/private/rules/flags.bzl
docs/build-docs.sh
docs/mkdocs/stylesheets/extra.css

1. Add horizontal scrollbar to overbox preformatted text.
2. Modifiy docstring to make generated pages look better.

Decorate docs

---

cuda/private/actions/compile.bzl
cuda/private/rules/cuda_library.bzl
cuda/private/rules/cuda_objects.bzl

Fixes #78
This changes to use basename indices to deduplicate as in cc rules.

Fix possibly conflict artifact names

---

.github/workflows/utilities-tests.yaml

Use windows-2019 for utilities tests

---

.github/workflows/build-tests.yaml
docs/mkdocs/stylesheets/extra.css
examples/if_cuda/README.md

Change-Id: Ic57b7986433f1618d3d2c403dae64e92aac3fc07

apply some pre-commit fixes

---

.pre-commit-config.yaml
cuda/templates/BUILD.local_toolchain_clang
cuda/templates/BUILD.local_toolchain_nvcc
cuda/templates/BUILD.local_toolchain_nvcc_msvc
examples/WORKSPACE.bazel

- use different buildifier pre-commit
- format with newest buildifier

upgrade buildifier

---

cuda/private/toolchain_configs/nvcc.bzl
cuda/private/toolchain_configs/nvcc_msvc.bzl
tests/flag/BUILD.bazel

Fix default dbg and fastbuild optimization level for nvcc

---

docs/WORKSPACE.bazel

Update stardoc to v0.6.2 manually

---

cuda/private/rules/cuda_objects.bzl

This will allow cuda_objects depends on another cuda_objects.

Let cuda_objects expose transitive objects

---

cuda/private/macros/cuda_test.bzl

Filter attrs properly for cuda_test

---

cuda/defs.bzl
cuda/private/macros/cuda_binary.bzl
docs/user_docs.bzl
examples/basic_macros/BUILD.bazel
examples/basic_macros/main.cu

This adds a similar macro as `cuda_test`.

Add cuda_binary macro

---

examples/WORKSPACE.bazel
renovate.json

Disallow autoupdate nccl

---

cuda/private/toolchain_configs/nvcc.bzl
cuda/private/toolchain_configs/nvcc_msvc.bzl

Check nvcc version before adding `--dopt on` flags

---

cuda/private/macros/cuda_binary.bzl
cuda/private/macros/cuda_test.bzl

fix: minor fix for cuda_binary and cuda_test macros attrs forwarding

---

cuda/private/template_helper.bzl

fix: fix clang detection on windows

---

cuda/private/actions/compile.bzl
cuda/private/actions/dlink.bzl
cuda/private/cuda_helper.bzl
cuda/private/toolchain_configs/clang.bzl
cuda/private/toolchain_configs/nvcc.bzl
cuda/private/toolchain_configs/nvcc_msvc.bzl
tests/flag/BUILD.bazel
tests/flag/flag_validation_test.bzl

fixes #344
guarded with features `cuda_host_use_copts`, `cuda_host_use_cxxopts` and `cuda_host_use_linkopts`

feat: optionally passthrough flags from cpp fragments

---

cuda/private/templates/BUILD.cudart

fix: also add additional_header_deps for @cuda//:cuda
